### ISSUE TITLE
マルチサーバ対応

### ISSUE THREAD

**Issue by highemerly** [hansodeclub/hagetter#15]
handon.club とかいう知らないサーバにしか対応していない

**Comment by osa9** [comment]
mstdn.jpに対応してるよ！！！

**Comment by osa9** [comment]
Duplicate of #1

**Comment by highemerly** [comment]
mstdn.jpが終わるまでにマルチサーバ対応してほしい

**Comment by highemerly** [comment]
> Duplicate of #1

重複issueを提出してしまい誠に申し訳ございませんでした。
