### ISSUE TITLE
hi, Is this project support SSR ?

### ISSUE THREAD

**Issue by stfenjobs** [hansodeclub/hagetter#21]
hi

the project is good, awesome !

Is this project support Server Side Rendering ?

thank you very much !

**Comment by osa9** [comment]
Yes, some pages support SSR using `getServerSideProps` feature added in Next.js 9.3.

Next.js Document
https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

Relative part in my project
https://github.com/hansodeclub/hagetter/search?q=getserversideprops&unscoped_q=getserversideprops

**Comment by stfenjobs** [comment]
thank you
